### ISSUE TITLE
Message: Methods with the same name as their class will not be constructors in a future version of PHP; phpFlickr_pager has a deprecated constructor

### ISSUE THREAD

**Issue by gskhattra87** [dan-coulter/phpflickr#85]
Message: Methods with the same name as their class will not be constructors in a future version of PHP; phpFlickr has a deprecated constructor

Filename: phpflickr/phpFlickr.php

Line Number: 25
----------------------------------------------------------------------------------------------------
Message: Methods with the same name as their class will not be constructors in a future version of PHP; phpFlickr_pager has a deprecated constructor

Filename: phpflickr/phpFlickr.php

Line Number: 1702

**Comment by TommyBloom** [comment]
Any news on this? I know that there is another issue that has a fork that apparently has a fix. That fork doesn't work with my drupal plugin.

**Comment by samwilson** [comment]
What error are you getting with your Drupal plugin?

**Comment by TheKLF99** [comment]
Change the function names on lines 62 and 1703 to read __construct instead of the class name - as long as nothing in the class calls the functions own name then it should work - I've searched the code and I can't see anything that calls the constructor inside the class.  I've just made that alteration myself and will see later on today if it works.

**Comment by samwilson** [comment]
I've fixed this issue in [my fork](https://github.com/samwilson/phpflickr) of this package.
